name: HideSpectator
description: Hides the grey player name when in spectator mode.
main: net.aerulion.hidespectator.HideSpectator
author: aerulion
version: '2.0.0'
api-version: '1.18'
depend: [ ProtocolLib ]
permissions:
  hidespectator.bypass:
    default: op
    description: Allows the player to still see the gray player name.